//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjercicioASP_EF1_4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno_Curso
    {
        public int idAlumnoCurso { get; set; }
        public Nullable<int> idAlumno { get; set; }
        public Nullable<int> idCursoImpartido { get; set; }
        public Nullable<int> nota { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Curso_Impartido Curso_Impartido { get; set; }
    }
}
