//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjercicioASP_EF1_4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso_Impartido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Curso_Impartido()
        {
            this.Alumno_Curso = new HashSet<Alumno_Curso>();
        }
    
        public int idCursoImpartido { get; set; }
        public Nullable<System.DateTime> Finicio { get; set; }
        public Nullable<System.DateTime> Ffin { get; set; }
        public Nullable<int> idProfesor { get; set; }
        public Nullable<int> idCurso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumno_Curso> Alumno_Curso { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual Profesor Profesor { get; set; }
    }
}
