<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="EjercicioASP10_3.WebForm1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <asp:CheckBox 
            ID="chkDelete"
            Text="Seleccione para eliminar"
            runat="server" />
        <asp:GridView 
            ID="grdOrders" 
            DataSourceID="sqlOrders"
            DataKeyNames="OrderId, CustomerId"
            AutoGenerateColumns="false"
            AllowPaging="true"
            AutoGenerateDeleteButton="true"
            runat="server">
            <Columns>
                <asp:BoundField 
                    HeaderText="Nº Pedido"
                    SortExpression="OrderId"
                    DataField="OrderId" />
                <asp:BoundField 
                    HeaderText="Cliente"
                    DataField="CustomerID" />
                <asp:BoundField 
                    HeaderText="Fecha Pedido"
                    DataField="OrderDate"
                    DataFormatString="{0:dd/mm/yy}" />
                <asp:BoundField 
                    HeaderText="Fecha invio"
                    DataField="ShippedDate"
                    DataFormatString="{0:dd/mm/yy}" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource 
            ID="sqlOrders"
            ConnectionString="<%$ ConnectionStrings:NorthWind %>" 
            SelectCommand="SELECT OrderID, CustomerID, OrderDate, ShippedDate FROM Orders"
            DeleteCommand="DELETE FROM Orders WHERE OrderId = @OrderId"
            OnDeleting="sqlOrders_Deleting"
            OnDeleted="sqlOrders_Deleted"
            runat="server">
            <DeleteParameters>
                <asp:Parameter Type="Int32" Name="OrderId" />
            </DeleteParameters>
        </asp:SqlDataSource>
        <br /><br />
        <asp:Label
            ID="lblDeleting"
            runat="server"
            visible="false"
            ForeColor="Red">
        </asp:Label>

    </div>
    </form>
</body>
</html>
