<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm2.aspx.cs" Inherits="Proyecto43_GridView.WebForm2" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <asp:GridView 
            ID="GridView1"
            DataSourceID="SqlDataSource1"
            AutoGenerateColumns="true"
            AutoGenerateDeleteButton="true"
            AutoGenerateEditButton="true"
            DataKeyName="CustomerID"
            runat="server">
        </asp:GridView>
        <asp:SqlDataSource 
            ID="SqlDataSource1" 
            ConnectionString="<%$ ConnectionStrings:NorthWind %>"
            SelectCommand="SELECT CustomerID, CompanyName, Address, City, PostalCode FROM Customers"
            UpdateCommand="UPDATE Customers SET CompanyName = @CompanyName, Address = @Address, City = @City, PostalCode = @PostalCode WHERE CustomerId = @CustomerId"
            DeleteCommand="DELETE FROM Customers WHERE CustomerId = @CustomerId"
            OnUpdated="SqlDataSource1_Updated"
            OnUpdating="SqlDataSource1_Updating"
            runat="server">
        </asp:SqlDataSource>
    </div>
    </form>
</body>
</html>
