<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm3.aspx.cs" Inherits="Proyecto43_GridView.WebForm3" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <asp:DropDownList 
            ID="role" 
            AutoPostBack="false"
            runat="server">
            <asp:ListItem Text=" - Seleccione Role - " Value="0"></asp:ListItem>
            <asp:ListItem Text="Usuario" Value="1"></asp:ListItem> 
            <asp:ListItem Text="Administrador" Value="2"></asp:ListItem>
        </asp:DropDownList>
        <asp:SqlDataSource 
            ID="SqlDataSource1" 
            ConnectionString="<%$ ConnectionStrings:NorthWind %>"
            SelectCommand="SELECT OD.OrderId, P.ProductName, P.UnitPrice, OD.Quantity, P.Discontinued FROM dbo.[Order Details] AS OD INNER JOIN Products AS P ON OD.ProductId = P.ProductId"
            DeleteCommand="DELETE FROM dbo.[Order Details] WHERE dbo.[Order Details].OrderId = @OrderId;
                           DELETE FROM dbo.Orders WHERE dbo.Orders.OrderId = @OrderId"
            OnDeleting="SqlDataSource1_Deleting"
            OnDeleted="SqlDataSource1_Deleted"
            runat="server">
        </asp:SqlDataSource>
        <asp:GridView 
            ID="GridView1" 
            DataSourceID="SqlDataSource1"
            DataKeyNames="OrderId"
            AutoGenerateColumn="false"
            AutoGenerateEditButton="true"
            AllowCustomPaging="true"
            AutoGenerateDeleteButton="true"
            OnRowCommand="GridView1_RowCommand"
            runat="server">
            <Columns>
                <asp:BoundField
                    DataField="OrderId"
                    HeaderText="Nº Pedido" />
                <asp:BoundField
                    DataField="ProductName"
                    HeaderText="Nombre Producto" />
                <asp:BoundField
                    DataField="UnitPrice"
                    HeaderText="Precio" />
                <asp:BoundField
                    DataField="Quantity"
                    HeaderText="Cantidad" />
                <asp:CheckBoxField
                    DataField="Discontinued"
                    HeaderText="Descuento" />

            </Columns>
        </asp:GridView>
        <asp:Label
            ID="label1"
            runat="server"
            visible="false"
            ForeColor="Red">
        </asp:Label>
    </div>
    </form>
</body>
</html>
